# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e84ff403d04f887cf9bf24f2e651366b2dab888bb26f93300de0e73d01f1d813fadbc5673d8b95f3661429efbfcf5f91095f845e082d85ed755bb9826e5930c2

test:
  secret_key_base: 45702c5fe5f48b1464fd5069f7a2ab823a7bf20807b64e487d4965e92dca3e88813774036d7497a91bc5b722ef71e539e483da4b2d61c5c762feb3f108f93910

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
